//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaserArt {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LaserArt.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ավելացնել ապրանք.
        /// </summary>
        public static string AddProduct {
            get {
                return ResourceManager.GetString("AddProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Սուշի.
        /// </summary>
        public static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Զամբյուղ.
        /// </summary>
        public static string Basket {
            get {
                return ResourceManager.GetString("Basket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Պատվիրել.
        /// </summary>
        public static string CreatOrder {
            get {
                return ResourceManager.GetString("CreatOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Հեռացնել.
        /// </summary>
        public static string DeleteProduct {
            get {
                return ResourceManager.GetString("DeleteProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Փոփոխել.
        /// </summary>
        public static string EditProduct {
            get {
                return ResourceManager.GetString("EditProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.Ավելացրեք զամբյուղ.
        /// </summary>
        public static string HowToBasket {
            get {
                return ResourceManager.GetString("HowToBasket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.Ընտրեք ուտեստը.
        /// </summary>
        public static string HowToFirst {
            get {
                return ResourceManager.GetString("HowToFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Պատվիրեք ձեր ցանկացած ուտեստը 3 քայլով.
        /// </summary>
        public static string HowToHeader {
            get {
                return ResourceManager.GetString("HowToHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.Պատվիրեք.
        /// </summary>
        public static string HowToOrder {
            get {
                return ResourceManager.GetString("HowToOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Հասցե.
        /// </summary>
        public static string OrderAddress {
            get {
                return ResourceManager.GetString("OrderAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ձեր պատվերը հաջողությամբ կատարված է.
        /// </summary>
        public static string OrderCreated {
            get {
                return ResourceManager.GetString("OrderCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Անուն.
        /// </summary>
        public static string OrderName {
            get {
                return ResourceManager.GetString("OrderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Հեռ․ համար.
        /// </summary>
        public static string OrderPhone {
            get {
                return ResourceManager.GetString("OrderPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Պատվերի գինը.
        /// </summary>
        public static string OrderPrice {
            get {
                return ResourceManager.GetString("OrderPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ազգանուն.
        /// </summary>
        public static string OrderSurname {
            get {
                return ResourceManager.GetString("OrderSurname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ԸՆՏՐԵՔ ՎՃԱՐՄԱՆ ԵՂԱՆԱԿԸ.
        /// </summary>
        public static string PaymentMethod {
            get {
                return ResourceManager.GetString("PaymentMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ԿԱՄ.
        /// </summary>
        public static string PaymentOr {
            get {
                return ResourceManager.GetString("PaymentOr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ՎՃԱՐՄԱՆ ՏԵՍԱԿԸ:.
        /// </summary>
        public static string PaymentType {
            get {
                return ResourceManager.GetString("PaymentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Քարտով.
        /// </summary>
        public static string PaymentTypeCard {
            get {
                return ResourceManager.GetString("PaymentTypeCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Կանխիկ.
        /// </summary>
        public static string PaymentTypeCash {
            get {
                return ResourceManager.GetString("PaymentTypeCash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Կատեգորիա.
        /// </summary>
        public static string ProductCategory {
            get {
                return ResourceManager.GetString("ProductCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Անուն.
        /// </summary>
        public static string ProductName {
            get {
                return ResourceManager.GetString("ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Գին.
        /// </summary>
        public static string ProductPrice {
            get {
                return ResourceManager.GetString("ProductPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Քանակ.
        /// </summary>
        public static string ProductQuantity {
            get {
                return ResourceManager.GetString("ProductQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ապրանքի մասին.
        /// </summary>
        public static string ProductSpecification {
            get {
                return ResourceManager.GetString("ProductSpecification", resourceCulture);
            }
        }
    }
}
